### ISSUE TITLE
New version: Book Chapter 10 problems don't run

### ISSUE THREAD

**Issue by antonwsu** [tomitrescak/clara-support#87]
Book -> Chapter 10 and Lecture 10 problems don't compile and don't run.

**Comment by antonwsu** [comment]
Ignore. Wrong Character file in the problem that I tried.

**Comment by tomitrescak** [comment]
Anton ... they do compile correctly to me. Can we go over this together?

**Comment by tomitrescak** [comment]
Pleaseclose this when you check them again ... I fixed the constructor problem and uploaded the fix

**Comment by antonwsu** [comment]
Still doesn't work. Compiles, but doesn't run. I'll email you the code I'm using for testing.

**Comment by antonwsu** [comment]
runs now, but need to make it consistent with the book
